// <auto-generated />
using APIManuel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIManuel.Migrations
{
    [DbContext(typeof(BauManuelContext))]
    [Migration("20210926193737_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("APIManuel.Models.Brinquedo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeTipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("tamanho")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Brinquedos");
                });
#pragma warning restore 612, 618
        }
    }
}
